//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcticCodeReview {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcticCodeReview.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add review comment (code or text can be selected).
        /// </summary>
        internal static string Message_Add_review_comment__code_or_text_can_be_selected {
            get {
                return ResourceManager.GetString("Message_Add_review_comment__code_or_text_can_be_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clean the current review and start new?.
        /// </summary>
        internal static string Message_Do_you_want_to_clean_the_current_review_and_start_new {
            get {
                return ResourceManager.GetString("Message_Do_you_want_to_clean_the_current_review_and_start_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Message_Error_0 {
            get {
                return ResourceManager.GetString("Message_Error_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on exicution of a command &quot;{0}&quot; with a parameter &quot;{1}&quot;.
        /// </summary>
        internal static string Message_Error_on_exicution_of_a_command_0_with_a_parameter_1 {
            get {
                return ResourceManager.GetString("Message_Error_on_exicution_of_a_command_0_with_a_parameter_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Review Comment.
        /// </summary>
        internal static string Title_Add_Review_Comment {
            get {
                return ResourceManager.GetString("Title_Add_Review_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Title_Comment {
            get {
                return ResourceManager.GetString("Title_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Title_File {
            get {
                return ResourceManager.GetString("Title_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hightlight with.
        /// </summary>
        internal static string Title_Hightlight_with {
            get {
                return ResourceManager.GetString("Title_Hightlight_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Title_Line {
            get {
                return ResourceManager.GetString("Title_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set forecolor.
        /// </summary>
        internal static string Title_Set_forecolor {
            get {
                return ResourceManager.GetString("Title_Set_forecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
    }
}
